# Generated by Django 6.0.5 on 2026-09-16 19:37

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_trials_consumed(apps, schema_editor):
    MedicineSubscription = apps.get_model('store', 'MedicineSubscription')
    Partner = apps.get_model('store', 'Partner')
    partner_ids = MedicineSubscription.objects.filter(
        trial_started_at__isnull=False
    ).values_list('partner_id', flat=True)
    Partner.objects.filter(id__in=partner_ids).update(medicine_trial_consumed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0094_customdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='medicine_trial_consumed',
            field=models.BooleanField(default=False, help_text='True once the partner has claimed their one-time free 60-day trial. Never reset.', verbose_name='Medicine Trial Consumed'),
        ),
        migrations.CreateModel(
            name='MedicineOrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(db_index=True, help_text='Date this order applies to (stock-out date)')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Manual ORDER quantity entered by the shopkeeper. 0 = not entered.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('exported', 'Exported'), ('sent', 'Sent'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('exported_filename', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_order_drafts', to='store.partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_order_drafts', to='store.medicineproduct')),
            ],
            options={
                'verbose_name': 'Medicine Order Draft',
                'verbose_name_plural': 'Medicine Order Drafts',
                'ordering': ['-order_date', '-updated'],
                'unique_together': {('partner', 'product', 'order_date')},
            },
        ),
        migrations.RunPython(
            code=mark_existing_trials_consumed,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
