# Generated by Django 6.0.5 on 2026-09-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0095_partner_medicine_trial_consumed_medicineorderdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='show_used_products',
            field=models.BooleanField(default=True, help_text='Full-width grid of used products on the homepage', verbose_name='Show "Hot Selling Used Product" section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_used_products_sidebar',
            field=models.BooleanField(default=True, help_text='When ON the right-sidebar lists show used products; falls back to Random list when there are no used products or this is OFF', verbose_name='Replace "Random Product List" sidebars with "Hot Selling Used Product"'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='used_products_heading',
            field=models.CharField(default='Hot Selling Used Product', max_length=200, verbose_name='Used products section heading'),
        ),
        migrations.AddField(
            model_name='partner',
            name='medicine_invoice_download_enabled',
            field=models.BooleanField(default=True, help_text='When ON, the Medicine POS shows a "Download Invoice" button after a sale so customers can download a PDF copy of the receipt.', verbose_name='Invoice Download Enabled'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', help_text='New or Used. Choosing "Used" automatically labels the product as Used.', max_length=10, verbose_name='Product Condition'),
        ),
    ]
