# Generated by Django 6.0.5 on 2026-09-17 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0096_product_condition_used_products_sidebar_invoice_download'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], default='home', help_text='Label for the address (Home / Office / Other). Existing field, stored value never rewritten.', max_length=20),
        ),
        migrations.CreateModel(
            name='AccountActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_2fa', 'Login (two-factor)'), ('logout', 'Logout'), ('password_change', 'Password changed'), ('2fa_enabled', 'Two-factor enabled'), ('2fa_disabled', 'Two-factor disabled'), ('email_verified', 'Email verified'), ('phone_verified', 'Phone verified'), ('email_changed', 'Email changed'), ('profile_updated', 'Profile updated'), ('avatar_updated', 'Avatar updated'), ('address_added', 'Address added'), ('address_updated', 'Address updated'), ('address_deleted', 'Address deleted'), ('default_address_changed', 'Default address changed'), ('sessions_revoked', 'Other sessions logged out'), ('preferences_updated', 'Notification preferences updated'), ('account_deactivated', 'Account deactivated')], max_length=40)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Activity Log',
                'verbose_name_plural': 'Account Activity Logs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('email_verify', 'Email Verification'), ('phone_verify', 'Phone Verification'), ('email_change', 'Email Change')], max_length=30)),
                ('code_hash', models.CharField(max_length=200)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('new_email', models.EmailField(blank=True, help_text='For email change: the address the code was sent to', max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'One Time Code',
                'verbose_name_plural': 'One Time Codes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two Factor Backup',
                'verbose_name_plural': 'Two Factor Backups',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=200)),
                ('used', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recovery Code',
                'verbose_name_plural': 'Recovery Codes',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_updates', models.BooleanField(default=True, verbose_name='Order updates')),
                ('review_replies', models.BooleanField(default=True, verbose_name='Review / Q&A replies')),
                ('promotions', models.BooleanField(default=False, verbose_name='Promotions & offers')),
                ('security_alerts', models.BooleanField(default=True, verbose_name='Security alerts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('', 'Not specified'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
