# Generated by Django 6.0.5 on 2026-09-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0097_address_address_type_accountactivitylog_onetimecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_2fa', 'Login (two-factor)'), ('logout', 'Logout'), ('password_change', 'Password changed'), ('2fa_enabled', 'Two-factor enabled'), ('2fa_disabled', 'Two-factor disabled'), ('email_verified', 'Email verified'), ('phone_verified', 'Phone verified'), ('email_changed', 'Email changed'), ('profile_updated', 'Profile updated'), ('avatar_updated', 'Avatar updated'), ('address_added', 'Address added'), ('address_updated', 'Address updated'), ('address_deleted', 'Address deleted'), ('default_address_changed', 'Default address changed'), ('sessions_revoked', 'Other sessions logged out'), ('preferences_updated', 'Notification preferences updated'), ('account_deactivated', 'Account deactivated'), ('security_failed', 'Security check failed')], max_length=40),
        ),
    ]
